package Vistas;

/** 
    @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
**/

import javax.swing.ImageIcon;

public class App_Menu extends javax.swing.JFrame {

     /**
     * Creates new form App_Menu
     */
    public App_Menu() {
        initComponents();
        //System.out.println("");
        setIconImage(new ImageIcon(getClass().getResource("/Images/logoULP.png")).getImage()); // logo de la esquina para la vista App_Menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiFormularioAlumno = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenu();
        jmiFormularioMaterias = new javax.swing.JMenuItem();
        jMenuEspaciador = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFondoLayout = new javax.swing.GroupLayout(jFondo);
        jFondo.setLayout(jFondoLayout);
        jFondoLayout.setHorizontalGroup(
            jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        jFondoLayout.setVerticalGroup(
            jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");

        jmiFormularioAlumno.setText("Formulario de Alumno");
        jmAlumno.add(jmiFormularioAlumno);

        jMenuBar1.add(jmAlumno);

        jmMaterias.setText("Materias");

        jmiFormularioMaterias.setText("Formulario de Materias");
        jmMaterias.add(jmiFormularioMaterias);

        jMenuBar1.add(jmMaterias);

        jMenuEspaciador.setText("                      ");
        jMenuEspaciador.setContentAreaFilled(false);
        jMenuEspaciador.setEnabled(false);
        jMenuBar1.add(jMenuEspaciador);

        jmSalir.setText("Salir");
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jFondo;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEspaciador;
    public javax.swing.JMenu jmAlumno;
    public javax.swing.JMenu jmMaterias;
    public javax.swing.JMenu jmSalir;
    public javax.swing.JMenuItem jmiFormularioAlumno;
    public javax.swing.JMenuItem jmiFormularioMaterias;
    // End of variables declaration//GEN-END:variables
}
