package Vistas;

/* @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
 */

public class VistaCargaNotas extends javax.swing.JInternalFrame {

    public VistaCargaNotas() {
        initComponents();
        setTitle("Manipulación de Notas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCargaNotas = new javax.swing.JLabel();
        jComboBListAlumCargaNotas = new javax.swing.JComboBox();
        jLSelectAlumn = new javax.swing.JLabel();
        jLSelectAlumn1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargaNotas = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalirCargaNotas = new javax.swing.JButton();
        jLbFondo = new javax.swing.JLabel();
        jLSelectAlumn2 = new javax.swing.JLabel();
        jLSelectAlumn3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 110, 232));

        jPanel1.setBackground(getBackground());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCargaNotas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLCargaNotas.setForeground(new java.awt.Color(255, 255, 255));
        jLCargaNotas.setText("Carga y modificación de Notas");
        jPanel1.add(jLCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jComboBListAlumCargaNotas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBListAlumCargaNotas.setToolTipText("");
        jPanel1.add(jComboBListAlumCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 620, 30));

        jLSelectAlumn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSelectAlumn.setForeground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn.setText("Seleccione un alumno:");
        jPanel1.add(jLSelectAlumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLSelectAlumn1.setBackground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLSelectAlumn1.setForeground(new java.awt.Color(0, 255, 255));
        jLSelectAlumn1.setText("(puede llevar decimales)");
        jPanel1.add(jLSelectAlumn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jTableCargaNotas.setAutoCreateRowSorter(true);
        jTableCargaNotas.setBackground(new java.awt.Color(102, 153, 255));
        jTableCargaNotas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableCargaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCargaNotas.setGridColor(new java.awt.Color(0, 0, 255));
        jTableCargaNotas.setRowHeight(24);
        jScrollPane1.setViewportView(jTableCargaNotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 820, 260));

        jButtonGuardar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jButtonSalirCargaNotas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSalirCargaNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salida.png"))); // NOI18N
        jButtonSalirCargaNotas.setText("Salir");
        jButtonSalirCargaNotas.setToolTipText("");
        jPanel1.add(jButtonSalirCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 140, -1));
        jPanel1.add(jLbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        jLSelectAlumn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLSelectAlumn2.setForeground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn2.setText("Aquí puedes modificar la Nota del alumno seleccionado:");
        jPanel1.add(jLSelectAlumn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLSelectAlumn3.setBackground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLSelectAlumn3.setForeground(new java.awt.Color(0, 255, 255));
        jLSelectAlumn3.setText("(modifica + enter + guardar)");
        jPanel1.add(jLSelectAlumn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonSalirCargaNotas;
    public javax.swing.JComboBox jComboBListAlumCargaNotas;
    private javax.swing.JLabel jLCargaNotas;
    private javax.swing.JLabel jLSelectAlumn;
    private javax.swing.JLabel jLSelectAlumn1;
    private javax.swing.JLabel jLSelectAlumn2;
    private javax.swing.JLabel jLSelectAlumn3;
    public javax.swing.JLabel jLbFondo;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableCargaNotas;
    // End of variables declaration//GEN-END:variables
}
